{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "685f6012-4274-4a97-8a56-f1a2a52d4dc6",
   "metadata": {},
   "outputs": [],
   "source": [
    "# coding=utf-8\n",
    "#######################################################\n",
    "# Программа Конвертер валют (USD)\n",
    "# python 3.x\n",
    "# WebForMySelf - Денис Новокщенов, 2026\n",
    "#######################################################\n",
    "# Writing sgiman, 2026\n",
    "\n",
    "#\n",
    "# сборка приложения в виде одного файла (без консоли)\n",
    "# pyinstaller -w currency_conv_ua.py\n",
    "# python -m nuitka --windows-console-mode=disable\n",
    "#\n",
    "\n",
    "#------------------------------------------------------\n",
    "# Курсы валют PRIVATBANK\n",
    "#------------------------------------------------------\n",
    "# https://api.privatbank.ua/#p24/exchange\n",
    "#\n",
    "# PRIVAT API:\n",
    "# Наличные\n",
    "# https://api.privatbank.ua/p24api/pubinfo?json&exchange&coursid=5\n",
    "# [{\"ccy\":\"EUR\",\"base_ccy\":\"UAH\",\"buy\":\"46.70000\",\"sale\":\"47.70000\"},\n",
    "# {\"ccy\":\"USD\",\"base_ccy\":\"UAH\",\"buy\":\"41.25000\",\"sale\":\"41.85000\"}]\n",
    "#\n",
    "# Безнал (cards)\n",
    "# https://api.privatbank.ua/p24api/pubinfo?exchange&coursid=11\n",
    "# [{\"ccy\":\"EUR\",\"base_ccy\":\"UAH\",\"buy\":\"46.80000\",\"sale\":\"47.84689\"},\n",
    "# {\"ccy\":\"USD\",\"base_ccy\":\"UAH\",\"buy\":\"41.35000\",\"sale\":\"41.84100\"}]\n",
    "#\n",
    "\n",
    "from tkinter import *\n",
    "from tkinter import ttk\n",
    "from tkinter import messagebox\n",
    "import urllib.request\n",
    "import json\n",
    "\n",
    "\n",
    "#================================\n",
    "#  W I N D O W\n",
    "#================================\n",
    "root = Tk()\n",
    "root.title('Privatbank (USD) - for Cards')\n",
    "root.geometry(\"400x250+700+300\")\n",
    "root.resizable(False, False)    # изменяемый размер окна (запретить W & H)\n",
    "root.iconbitmap('nt.ico')                   # иконка\n",
    "START_AMOUNT = 100                          # SUMA (default)\n",
    "\n",
    "\n",
    "#================================\n",
    "#  F u n c t i o n s\n",
    "#================================\n",
    "def exchange():\n",
    "    # очистить поля валют\n",
    "    e_uah.delete(0, END)\n",
    "    # Попытка конвертировать валюту\n",
    "    try:\n",
    "        e_uah.insert(0, round(float(e_usd.get()) * float(JSON_object[1]['sale']), 2))\n",
    "    except:\n",
    "        messagebox.showwarning('Warning', 'Проверьте введенную сумму')\n",
    "\n",
    "\n",
    "# Попытка получить JSON (от API PRIVAT)\n",
    "try:\n",
    "    # html = urllib.request.urlopen('https://api.privatbank.ua/p24api/pubinfo?json&exchange&coursid=5') # наличные\n",
    "    html = urllib.request.urlopen('https://api.privatbank.ua/p24api/pubinfo?exchange&coursid=11')        # безнал (cards)\n",
    "    data = html.read()\n",
    "    JSON_object = json.loads(data)  # текущие данные валют\n",
    "except:\n",
    "    messagebox.showerror(\"Error\", 'Ошибка получения курсов валют.\\nНет подключения к интернет.')\n",
    "    # root.destroy()  # quit (exit)\n",
    "\n",
    "#---------------------------------\n",
    "# Header Frame\n",
    "#---------------------------------\n",
    "header_frame = Frame(root)\n",
    "header_frame.pack(fill=X)\n",
    "\n",
    "# Равномерное размещение колонок заголовков по весу (таблица)\n",
    "header_frame.grid_columnconfigure(0, weight=1)\n",
    "header_frame.grid_columnconfigure(1, weight=1)\n",
    "header_frame.grid_columnconfigure(2, weight=1)\n",
    "\n",
    "# Header (ряд 0) - чёрный\n",
    "h_currency = Label(header_frame, text=\"Валюта\", bg=\"#000\", fg=\"#fff\", font=\"Arial 12 bold\")\n",
    "h_currency.grid(row=0, column=0, sticky=EW)\n",
    "h_buy = Label(header_frame, text=\"Покупка\", bg=\"orange\", fg=\"white\", font=\"Arial 12 bold\")\n",
    "h_buy.grid(row=0, column=1, sticky=EW)\n",
    "h_sale = Label(header_frame, text=\"Продажа\", bg=\"blue\", fg=\"white\", font=\"Arial 12 bold\")\n",
    "h_sale.grid(row=0, column=2, sticky=EW)\n",
    "\n",
    "# USD course (ряд 1)\n",
    "usd_currency = Label(header_frame, text=\"USD\", bg=\"#ccc\", font=\"Arial 10\")\n",
    "usd_currency.grid(row=1, column=0, sticky=EW)\n",
    "usd_buy = Label(header_frame, text=JSON_object[1]['buy'], bg=\"#ccc\", font=\"Arial 10\")\n",
    "usd_buy.grid(row=1, column=1, sticky=EW)\n",
    "usd_sale = Label(header_frame, text=JSON_object[1]['sale'], bg=\"#ccc\", font=\"Arial 10\")\n",
    "usd_sale.grid(row=1, column=2, sticky=EW)\n",
    "\n",
    "# EUR course (ряд 2) - серый\n",
    "# eur_currency = Label(header_frame, text=\"EUR\", font=\"Arial 10\")\n",
    "# eur_currency.grid(row=2, column=0, sticky=EW)\n",
    "# eur_buy = Label(header_frame, text=JSON_object[0]['buy'],  font=\"Arial 10\")\n",
    "# eur_buy.grid(row=2, column=1, sticky=EW)\n",
    "# eur_sale = Label(header_frame, text=JSON_object[0]['sale'], font=\"Arial 10\")\n",
    "# eur_sale.grid(row=2, column=2, sticky=EW)\n",
    "\n",
    "# Calc Frame\n",
    "calc_frame = Frame(root, bg=\"#fff\")\n",
    "calc_frame.pack(expand=1, fill=BOTH)                  # разместить и растянуть\n",
    "calc_frame.grid_columnconfigure(1, weight=1)    # на всю ширину фрейма\n",
    "\n",
    "# USD (вводимая сумма в USD)\n",
    "l_usd = Label(calc_frame, text=\"USD:\", bg=\"#fff\", font=\"Arial 10 bold\")\n",
    "l_usd.grid(row=0, column=0, padx=10)\n",
    "e_usd = ttk.Entry(calc_frame, justify=CENTER, font=\"Arial 10\")\n",
    "e_usd.grid(row=0, column=1, columnspan=2, pady=10, padx=10, sticky=EW)\n",
    "e_usd.insert(0, START_AMOUNT)   # подставить сумму по умолчанию\n",
    "\n",
    "#-----------------------\n",
    "# Button (\"Обмен\")\n",
    "#-----------------------\n",
    "# btn_calc = ttk.Button(calc_frame, text=\"Обмен\", command=exchange)   # ttk style\n",
    "btn_calc = Button(calc_frame, text=\"Обмен\", font=(\"Arial\",'10','bold'), fg=\"white\", bg=\"red\", command=exchange)  # standard style\n",
    "btn_calc.grid(row=1, column=1, columnspan=2, sticky=EW, padx=10)\n",
    "\n",
    "#========================\n",
    "#  R E S U L T (table)\n",
    "#========================\n",
    "# Result Frame\n",
    "res_frame = Frame(root)\n",
    "res_frame.pack(expand=1, fill=BOTH, pady=5)\n",
    "res_frame.grid_columnconfigure(1, weight=1)\n",
    "\n",
    "# UAH (entry)\n",
    "l_uah = Label(res_frame, text=\"UAH:\", font=\"Arial 10 bold\")\n",
    "l_uah.grid(row=2, column=0)\n",
    "e_uah = ttk.Entry(res_frame, justify=CENTER, font=\"Arial 10\")\n",
    "e_uah.grid(row=2, column=1, columnspan=2, padx=10, sticky=EW)\n",
    "e_uah.insert(0, round(START_AMOUNT * float(JSON_object[1]['sale']), 2))     # конвертация USD\n",
    "\n",
    "# # EUR (entry)\n",
    "# l_eur = Label(res_frame, text=\"EUR:\", font=\"Arial 10 bold\")\n",
    "# l_eur.grid(row=3, column=0)\n",
    "# e_eur = ttk.Entry(res_frame, justify=CENTER, font=\"Arial 10\")\n",
    "# e_eur.grid(row=3, column=1, columnspan=2, padx=10, sticky=EW)\n",
    "# e_eur.insert(0, round(START_AMOUNT * float(JSON_object[1]['sale']), 2))     # конвертация EUR\n",
    "\n",
    "\n",
    "root.mainloop()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "name": ""
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
